apiVersion: v1 # based on kind
kind: Pod # can be Pod, Service, Replica Set or Deployment
metadata: # Should be a dictionary
  name: reddis-pod
  labels:
    name: reddis-pod
    app: demo-voting-app
spec: # Should be a list
  containers:
    - name: redis
      image: redis # redis image docker hub
      ports: 
        - containerPort: 6379 # Port of the container which is exposed for the service
    