apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  namespace: learning
data:
  APP_ENV: "production"
  APP_PORT: "9090"
  DB_HOST: "prod-db.internal.net"
  ENABLE_DISCOUNTS: "true"